CREATE SCHEMA "rio_da_prata";
--> statement-breakpoint
CREATE SEQUENCE "rio_da_prata"."Bacia_RioDaPrata_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "rio_da_prata"."Rio da Prata - Leito_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1;--> statement-breakpoint
CREATE TABLE "rio_da_prata"."acoes" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"latitude" numeric(10, 6),
	"longitude" numeric(10, 6),
	"elevation" numeric(8, 2),
	"time" timestamp,
	"descricao" varchar(255),
	"mes" varchar(50),
	"atuacao" varchar(100),
	"acao" varchar(100),
	"geom" geometry(point)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."Bacia_Rio_Da_Prata" (
	"id" serial PRIMARY KEY NOT NULL,
	"geom" geometry(point),
	"hybas_id" bigint,
	"next_down" bigint,
	"next_sink" bigint,
	"main_bas" bigint,
	"dist_sink" double precision,
	"dist_main" double precision,
	"sub_area" double precision,
	"up_area" double precision,
	"pfaf_id" bigint,
	"endo" integer,
	"coast" integer,
	"order_" integer,
	"sort" integer,
	"dis_m3_pyr" double precision,
	"dis_m3_pmn" double precision,
	"dis_m3_pmx" double precision,
	"run_mm_syr" integer,
	"inu_pc_smn" integer,
	"inu_pc_umn" integer,
	"inu_pc_smx" integer,
	"inu_pc_umx" integer,
	"inu_pc_slt" integer,
	"inu_pc_ult" integer,
	"lka_pc_sse" integer,
	"lka_pc_use" integer,
	"lkv_mc_usu" integer,
	"rev_mc_usu" integer,
	"dor_pc_pva" integer,
	"ria_ha_ssu" double precision,
	"ria_ha_usu" double precision,
	"riv_tc_ssu" double precision,
	"riv_tc_usu" double precision,
	"gwt_cm_sav" integer,
	"ele_mt_sav" integer,
	"ele_mt_uav" integer,
	"ele_mt_smn" integer,
	"ele_mt_smx" integer,
	"slp_dg_sav" integer,
	"slp_dg_uav" integer,
	"sgr_dk_sav" integer,
	"clz_cl_smj" integer,
	"cls_cl_smj" integer,
	"tmp_dc_syr" integer,
	"tmp_dc_uyr" integer,
	"tmp_dc_smn" integer,
	"tmp_dc_smx" integer,
	"tmp_dc_s01" integer,
	"tmp_dc_s02" integer,
	"tmp_dc_s03" integer,
	"tmp_dc_s04" integer,
	"tmp_dc_s05" integer,
	"tmp_dc_s06" integer,
	"tmp_dc_s07" integer,
	"tmp_dc_s08" integer,
	"tmp_dc_s09" integer,
	"tmp_dc_s10" integer,
	"tmp_dc_s11" integer,
	"tmp_dc_s12" integer,
	"pre_mm_syr" integer,
	"pre_mm_uyr" integer,
	"pre_mm_s01" integer,
	"pre_mm_s02" integer,
	"pre_mm_s03" integer,
	"pre_mm_s04" integer,
	"pre_mm_s05" integer,
	"pre_mm_s06" integer,
	"pre_mm_s07" integer,
	"pre_mm_s08" integer,
	"pre_mm_s09" integer,
	"pre_mm_s10" integer,
	"pre_mm_s11" integer,
	"pre_mm_s12" integer,
	"pet_mm_syr" integer,
	"pet_mm_uyr" integer,
	"pet_mm_s01" integer,
	"pet_mm_s02" integer,
	"pet_mm_s03" integer,
	"pet_mm_s04" integer,
	"pet_mm_s05" integer,
	"pet_mm_s06" integer,
	"pet_mm_s07" integer,
	"pet_mm_s08" integer,
	"pet_mm_s09" integer,
	"pet_mm_s10" integer,
	"pet_mm_s11" integer,
	"pet_mm_s12" integer,
	"aet_mm_syr" integer,
	"aet_mm_uyr" integer,
	"aet_mm_s01" integer,
	"aet_mm_s02" integer,
	"aet_mm_s03" integer,
	"aet_mm_s04" integer,
	"aet_mm_s05" integer,
	"aet_mm_s06" integer,
	"aet_mm_s07" integer,
	"aet_mm_s08" integer,
	"aet_mm_s09" integer,
	"aet_mm_s10" integer,
	"aet_mm_s11" integer,
	"aet_mm_s12" integer,
	"ari_ix_sav" integer,
	"ari_ix_uav" integer,
	"cmi_ix_syr" integer,
	"cmi_ix_uyr" integer,
	"cmi_ix_s01" integer,
	"cmi_ix_s02" integer,
	"cmi_ix_s03" integer,
	"cmi_ix_s04" integer,
	"cmi_ix_s05" integer,
	"cmi_ix_s06" integer,
	"cmi_ix_s07" integer,
	"cmi_ix_s08" integer,
	"cmi_ix_s09" integer,
	"cmi_ix_s10" integer,
	"cmi_ix_s11" integer,
	"cmi_ix_s12" integer,
	"snw_pc_syr" integer,
	"snw_pc_uyr" integer,
	"snw_pc_smx" integer,
	"snw_pc_s01" integer,
	"snw_pc_s02" integer,
	"snw_pc_s03" integer,
	"snw_pc_s04" integer,
	"snw_pc_s05" integer,
	"snw_pc_s06" integer,
	"snw_pc_s07" integer,
	"snw_pc_s08" integer,
	"snw_pc_s09" integer,
	"snw_pc_s10" integer,
	"snw_pc_s11" integer,
	"snw_pc_s12" integer,
	"glc_cl_smj" integer,
	"glc_pc_s01" integer,
	"glc_pc_s02" integer,
	"glc_pc_s03" integer,
	"glc_pc_s04" integer,
	"glc_pc_s05" integer,
	"glc_pc_s06" integer,
	"glc_pc_s07" integer,
	"glc_pc_s08" integer,
	"glc_pc_s09" integer,
	"glc_pc_s10" integer,
	"glc_pc_s11" integer,
	"glc_pc_s12" integer,
	"glc_pc_s13" integer,
	"glc_pc_s14" integer,
	"glc_pc_s15" integer,
	"glc_pc_s16" integer,
	"glc_pc_s17" integer,
	"glc_pc_s18" integer,
	"glc_pc_s19" integer,
	"glc_pc_s20" integer,
	"glc_pc_s21" integer,
	"glc_pc_s22" integer,
	"glc_pc_u01" integer,
	"glc_pc_u02" integer,
	"glc_pc_u03" integer,
	"glc_pc_u04" integer,
	"glc_pc_u05" integer,
	"glc_pc_u06" integer,
	"glc_pc_u07" integer,
	"glc_pc_u08" integer,
	"glc_pc_u09" integer,
	"glc_pc_u10" integer,
	"glc_pc_u11" integer,
	"glc_pc_u12" integer,
	"glc_pc_u13" integer,
	"glc_pc_u14" integer,
	"glc_pc_u15" integer,
	"glc_pc_u16" integer,
	"glc_pc_u17" integer,
	"glc_pc_u18" integer,
	"glc_pc_u19" integer,
	"glc_pc_u20" integer,
	"glc_pc_u21" integer,
	"glc_pc_u22" integer,
	"pnv_cl_smj" integer,
	"pnv_pc_s01" integer,
	"pnv_pc_s02" integer,
	"pnv_pc_s03" integer,
	"pnv_pc_s04" integer,
	"pnv_pc_s05" integer,
	"pnv_pc_s06" integer,
	"pnv_pc_s07" integer,
	"pnv_pc_s08" integer,
	"pnv_pc_s09" integer,
	"pnv_pc_s10" integer,
	"pnv_pc_s11" integer,
	"pnv_pc_s12" integer,
	"pnv_pc_s13" integer,
	"pnv_pc_s14" integer,
	"pnv_pc_s15" integer,
	"pnv_pc_u01" integer,
	"pnv_pc_u02" integer,
	"pnv_pc_u03" integer,
	"pnv_pc_u04" integer,
	"pnv_pc_u05" integer,
	"pnv_pc_u06" integer,
	"pnv_pc_u07" integer,
	"pnv_pc_u08" integer,
	"pnv_pc_u09" integer,
	"pnv_pc_u10" integer,
	"pnv_pc_u11" integer,
	"pnv_pc_u12" integer,
	"pnv_pc_u13" integer,
	"pnv_pc_u14" integer,
	"pnv_pc_u15" integer,
	"wet_cl_smj" integer,
	"wet_pc_sg1" integer,
	"wet_pc_ug1" integer,
	"wet_pc_sg2" integer,
	"wet_pc_ug2" integer,
	"wet_pc_s01" integer,
	"wet_pc_s02" integer,
	"wet_pc_s03" integer,
	"wet_pc_s04" integer,
	"wet_pc_s05" integer,
	"wet_pc_s06" integer,
	"wet_pc_s07" integer,
	"wet_pc_s08" integer,
	"wet_pc_s09" integer,
	"wet_pc_u01" integer,
	"wet_pc_u02" integer,
	"wet_pc_u03" integer,
	"wet_pc_u04" integer,
	"wet_pc_u05" integer,
	"wet_pc_u06" integer,
	"wet_pc_u07" integer,
	"wet_pc_u08" integer,
	"wet_pc_u09" integer,
	"for_pc_sse" integer,
	"for_pc_use" integer,
	"crp_pc_sse" integer,
	"crp_pc_use" integer,
	"pst_pc_sse" integer,
	"pst_pc_use" integer,
	"ire_pc_sse" integer,
	"ire_pc_use" integer,
	"gla_pc_sse" integer,
	"gla_pc_use" integer,
	"prm_pc_sse" integer,
	"prm_pc_use" integer,
	"pac_pc_sse" integer,
	"pac_pc_use" integer,
	"tbi_cl_smj" integer,
	"tec_cl_smj" integer,
	"fmh_cl_smj" integer,
	"fec_cl_smj" integer,
	"cly_pc_sav" integer,
	"cly_pc_uav" integer,
	"slt_pc_sav" integer,
	"slt_pc_uav" integer,
	"snd_pc_sav" integer,
	"snd_pc_uav" integer,
	"soc_th_sav" integer,
	"soc_th_uav" integer,
	"swc_pc_syr" integer,
	"swc_pc_uyr" integer,
	"swc_pc_s01" integer,
	"swc_pc_s02" integer,
	"swc_pc_s03" integer,
	"swc_pc_s04" integer,
	"swc_pc_s05" integer,
	"swc_pc_s06" integer,
	"swc_pc_s07" integer,
	"swc_pc_s08" integer,
	"swc_pc_s09" integer,
	"swc_pc_s10" integer,
	"swc_pc_s11" integer,
	"swc_pc_s12" integer,
	"lit_cl_smj" integer,
	"kar_pc_sse" integer,
	"kar_pc_use" integer,
	"ero_kh_sav" integer,
	"ero_kh_uav" integer,
	"pop_ct_ssu" double precision,
	"pop_ct_usu" double precision,
	"ppd_pk_sav" double precision,
	"ppd_pk_uav" double precision,
	"urb_pc_sse" integer,
	"urb_pc_use" integer,
	"nli_ix_sav" integer,
	"nli_ix_uav" integer,
	"rdd_mk_sav" integer,
	"rdd_mk_uav" integer,
	"hft_ix_s93" integer,
	"hft_ix_u93" integer,
	"hft_ix_s09" integer,
	"hft_ix_u09" integer,
	"gad_id_smj" integer,
	"gdp_ud_sav" integer,
	"gdp_ud_ssu" bigint,
	"gdp_ud_usu" bigint,
	"hdi_ix_sav" integer
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."Banhado_Rio_Da_Prata" (
	"id" bigint PRIMARY KEY NOT NULL,
	"geom" geometry(point)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."deque_de_pedras" (
	"id" serial PRIMARY KEY NOT NULL,
	"local" varchar(255),
	"mes" varchar(50),
	"data" date,
	"turbidez" numeric(5, 2),
	"secchi_vertical" numeric(5, 2),
	"secchi_horizontal" numeric(5, 2),
	"chuva" numeric(5, 2)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."desmatamento" (
	"id" serial PRIMARY KEY NOT NULL,
	"alertid" text,
	"alertcode" text,
	"alertha" double precision,
	"source" text,
	"detectat" text,
	"detectyear" integer,
	"state" text,
	"stateha" double precision,
	"geom" geometry(point)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."estradas" (
	"id" serial PRIMARY KEY NOT NULL,
	"nome" varchar(255),
	"tipo" varchar(100),
	"codigo" varchar(50),
	"geom" geometry(point)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."Leito_Rio_Da_Prata" (
	"id" serial PRIMARY KEY NOT NULL,
	"geom" geometry(point),
	"name" varchar(254),
	"descriptio" varchar(254),
	"timestamp" varchar(24),
	"begin" varchar(24),
	"end" varchar(24),
	"altitudemo" varchar(254),
	"tessellate" bigint,
	"extrude" bigint,
	"visibility" bigint,
	"draworder" bigint,
	"icon" varchar(254),
	"descript_1" varchar(254),
	"altitude_1" varchar(254),
	"gm_layer" varchar(254),
	"gm_type" varchar(254),
	"layer" varchar(254),
	"compriment" numeric,
	"metros" double precision
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."ponte_do_cure" (
	"id" serial PRIMARY KEY NOT NULL,
	"local" varchar(255),
	"mes" varchar(50),
	"data" date,
	"chuva" numeric(5, 2),
	"nivel" numeric(5, 2),
	"visibilidade" varchar(50)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."propriedades" (
	"id" serial PRIMARY KEY NOT NULL,
	"cod_tema" varchar(50),
	"nom_tema" varchar(100),
	"cod_imovel" varchar(100),
	"mod_fiscal" double precision,
	"num_area" double precision,
	"ind_status" varchar(20),
	"ind_tipo" varchar(20),
	"des_condic" text,
	"municipio" varchar(100),
	"geom" geometry(point)
);
--> statement-breakpoint
CREATE TABLE "rio_da_prata"."raw_firms" (
	"latitude" double precision,
	"longitude" double precision,
	"bright_ti4" double precision,
	"scan" double precision,
	"track" double precision,
	"acq_date" date,
	"acq_time" text,
	"satellite" text,
	"instrument" text,
	"confidence" text,
	"version" text,
	"bright_ti5" double precision,
	"frp" double precision,
	"daynight" text,
	"type" text,
	"hora_deteccao" time,
	"geom" geometry(point)
);
